In [ ]:
a,b=3,'3'
print(a,b)

3 3


In [ ]:
# int() 함수를 이용해 문자를 숫자로 변환
b=int(b)
b

3

In [ ]:
# str()함수를 이용해 숫자를 문자로 변환
a=str(a)
a

'3'

# 1111….1111은 1이 2020번 반복된 큰 숫자이다. 이 숫자를 11,111,111로 나눈 나머지를 구해보아라.

In [ ]:
B_N='1'*2020 # '1'이라는 문자를 2020번 반복한다.
N=int(B_N) # B_N이란 문자열을 integer형으로 변환시킨다.
N%11111111 # N을 11,111,111로 나눈 나머지를 구한다.

1111

In [ ]:
A="1243"
int(A)

1243

In [ ]:
str(1243)

'1243'

In [ ]:
15//2 # 몫을 구함

7

In [ ]:
15%4 # 나머지를 구함

3

In [ ]:
4**3 # 거듭제곱구하기

64

In [ ]:
a,b='컴퓨터','파이썬'
a+b

'컴퓨터파이썬'

In [ ]:
a*3

'컴퓨터컴퓨터컴퓨터'

# 1부터 10000사이의 정수 1000개가 random하게 흩어져 있다. 이 숫자를 작은 순서대로 정렬하여 5번째의 숫자를 출력해 보자.

In [ ]:
import numpy as np # numpy라는 패키지를 np의 별명으로 불러온다.
# numpy.random 아래에 있는 randint()함수를 호출한다.
# randint(a,b,size=c)는 a부터 b-1까지의 정수를 c개 무작위 추출시킨다.
D=np.random.randint(1,10000,size=1000)
sort_1=sorted(D) # 오름차순 정렬
sort_2=sorted(D,reverse=True) # 내림차순 정렬
print('5번째 작은 수는',sort_1[4],'입니다')
print('5번째 큰 수는',sort_2[4],'입니다.')

5번째 작은 수는 37 입니다
5번째 큰 수는 9950 입니다.


In [ ]:
# 첫번째 숫자: 방법 1
D[0]

9577

In [ ]:
# # 첫번째 숫자: 방법 2
D[-1000]

9577

In [ ]:
# 마지막 숫자: 방법 1
D[999]

6569

In [ ]:
# 마지막 숫자: 방법 2
D[999]

6569

In [ ]:
# 처음부터 5번째까지의 숫자
D[:5]

array([9577, 6954, 2923, 5327,  176])

In [ ]:
# 3번째 부터 5번째까지의 숫자
D[2:5]

array([2923, 5327,  176])

In [ ]:
# 마지막 5개 숫자
D[-5:]

array([4856, 7351, 7220, 2217, 6569])

In [ ]:
# 998번째부터 999번째 숫자 선택: 방법1
D[997:999]

array([7220, 2217])

In [ ]:
# 998번째부터 999번째 숫자 선택: 방법2
D[-3:-1]

array([7220, 2217])

# 집합 A={1,2,3}, 집합 B={3,4,5}라고 한다. 차집합 A-B, 합집합 A∪B, 교집합 A∩B 등을 구하여 보아라.

In [ ]:
A,B=[1,2,3],[3,4,5]
# 내장함수 set()을 이용하여 집합으로 변형
A,B=set(A),set(B)
A-B

{1, 2}

In [ ]:
A,B={1,2,3},{3,4,5}
A-B

{1, 2}

In [ ]:
A.union(B) # 내장함수 union() 사용

{1, 2, 3, 4, 5}

In [ ]:
A.intersection(B) # 내장함수 intersection() 사용

{3}

In [ ]:
# Dictionary 자료형은 인덱싱을 문자열로 한다는 차이가 있다.
A={'사과':0,'배':2,'오렌지':11} # 사과,배,오렌지는 key값이라고 부른다.
A['사과']

0

In [ ]:
list(B)

[3, 4, 5]

# 아래와 같은 자료를 생성해 보아라.

In [ ]:
# i는 10부터 20까지 1씩 증가
# j는 1부터 10까지 1씩 증가
[[i+j for i in range(10,21)] for j in range(1,11)]

[[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
 [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
 [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
 [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
 [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
 [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
 [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
 [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
 [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]

In [ ]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


# C_pairs=[‘USDJPY’,’USDGBP’,’USDCHF’,’USDCAD’,’AUDUSD’,’NZDUSD’,’KRWUSD’,’KRWJPY’]는 여러나라의 화폐단위 정보가 Mixing되어 들어 있다. 몇 종류의 화폐 정보가 들어 있는지 출력해 보아라.

In [ ]:
# i는 0부터 9까지
D0=[i for i in range(10)]
len(D0)

10

In [ ]:
# (0,0),(1,2),...,(9,18)의 순서쌍을 리스트로 저장
D1=[(i,2*i) for i in range(10)]
len(D1)

10

In [ ]:
D2=[[(i,2*i) for i in range(10)]]
len(D2)

1

In [ ]:
len(D2[0]) # D2의 첫번째에 들어 있는 원소의 개수

10

In [ ]:
D4=[1,2,2,2,3,3] # 리스트 자료형
D5=set(D4) # set 형태로 변환
(len(D4),len(D5))

(6, 3)

In [ ]:
C_pairs=['USDJPY','USDGBP','USDCHF','USDCAD','AUDUSD','NZDUSD','KRWUSD','KRWJPY']
L=[] # 빈 list 자료 생성
for item in C_pairs: # C_pairs에 있는 item을 하나씩 가져와서
    L.append(item[:3]) # item의 첫 세글자를 선택하여 L 리스트에 추가
    L.append(item[-3:]) # item의 마지막 세글자를 L리스트에 추가
L=set(L) # 리스트 L을 집합으로 바꾸면 중복되는 것들을 제거할 수 있다.
print(L) # 집합 L 출력
print('화폐의 종류는 총 {0}개입니다.'.format(len(L)))

{'GBP', 'USD', 'CAD', 'KRW', 'AUD', 'JPY', 'CHF', 'NZD'}
화폐의 종류는 총 8개입니다.


In [ ]:
# 연결해서 사용
for i in range(5): #i를 0부터 4까지 증가
    print('출력되는 숫자는', i, '입니다')

출력되는 숫자는 0 입니다
출력되는 숫자는 1 입니다
출력되는 숫자는 2 입니다
출력되는 숫자는 3 입니다
출력되는 숫자는 4 입니다


In [ ]:
# f''형태로 사용
for i in range(5): #i를 0부터 4까지 증가
    print(f'출력되는 숫자는 {i}입니다')

출력되는 숫자는 0입니다
출력되는 숫자는 1입니다
출력되는 숫자는 2입니다
출력되는 숫자는 3입니다
출력되는 숫자는 4입니다


In [ ]:
# format과 같이 사용
for i in range(5): #i를 0부터 4까지 증가
    print('출력되는 숫자는 {0}입니다'.format(i))

출력되는 숫자는 0입니다
출력되는 숫자는 1입니다
출력되는 숫자는 2입니다
출력되는 숫자는 3입니다
출력되는 숫자는 4입니다


In [ ]:
for i in range(5): #i를 0부터 4까지 증가
    print('출력되는 숫자는 {0} \n그리고 이 수의 2배인 {1}'.format(i,2*i))

출력되는 숫자는 0 
그리고 이 수의 2배인 0
출력되는 숫자는 1 
그리고 이 수의 2배인 2
출력되는 숫자는 2 
그리고 이 수의 2배인 4
출력되는 숫자는 3 
그리고 이 수의 2배인 6
출력되는 숫자는 4 
그리고 이 수의 2배인 8


# 아래와 같은 사전형의 자료가 있다. 사전의 key값에 해당하는 value 값을 모두 10배씩 바꾸려면 어떻게 해야 하는가?

In [ ]:
import numpy as np
dic={f'C0{i}':np.random.rand() for i in range(10)}
dic

{'C00': 0.9773725462810825,
 'C01': 0.06347890962042713,
 'C02': 0.23589006723320805,
 'C03': 0.5699004843210257,
 'C04': 0.9712382877250477,
 'C05': 0.018380358352138026,
 'C06': 0.842347168005328,
 'C07': 0.307936184081091,
 'C08': 0.8453291672604201,
 'C09': 0.7560001002869453}

In [ ]:
# value 값을 모두 10배 하려면...
# 아래 반복문에서 i에는 key값이, j에는 해당하는 value값이 읽어진다.
for i,j in dic.items():
    dic[i]=j*10
dic

{'C00': 9.773725462810825,
 'C01': 0.6347890962042713,
 'C02': 2.3589006723320805,
 'C03': 5.699004843210257,
 'C04': 9.712382877250477,
 'C05': 0.18380358352138026,
 'C06': 8.42347168005328,
 'C07': 3.0793618408109102,
 'C08': 8.4532916726042,
 'C09': 7.560001002869453}

# 1부터 10까지 더하여라.

In [ ]:
# for 문의 형식
L=['A','B','C','D']
# L에 있는 원소들을 하나씩 변화시켜 가면서 모두 선택하고 끝낸다.
for item in L: # 반드시 ':'을 뒤에 붙일 것!
    print(item) # indentation 필요

A
B
C
D


In [ ]:
Ans=0
# 반복문에서 사용하는 range(N)은 0부터 N-1까지 1씩 증가시킨다.
for i in range(11): # 반드시 ':'을 조건 뒤에 붙일 것!
    Ans=Ans+i
Ans

55

In [ ]:
import numpy as np
# 리스트[]의 자료안에 for 문을 사용하여 자료를 미리 만든 후
# numpy.sum() 함수를 활용해 답을 구한다.
D1=[i for i in range(11)]
print('D1=',D1)
print('D1 자료의 총합은:',np.sum(D1))

D1= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
D1 자료의 총합은: 55


In [ ]:
# while 문의 사용
i,Ans=1,0 # i=1, Ans=0을 대입
while i <=10: # i가 10이하면 계속 수행, 문장 끝에 ':'붙인다.
    Ans=Ans+i # 직전 Ans에 i를 더한다
    i=i+1 # 직전 i에 1을 더한다.
Ans

55

# 1부터 1000까지의 자연수 중 3의 배수가 아닌 숫자들을 모두 더하여라.

In [ ]:
Ans=0
# 반복문에서 사용되는 객체 range(a,b,c)는 a부터 b-1까지 c씩 증가하는 숫자를 만들어낸다.
# range(a,b)는 a부터 b-1까지 1씩 증가하는 숫자를 만들어낸다.
# range(a)는 0부터 시작해서 a-1까지 1씩 증가하는 숫자를 만들어낸다.
for i in range(1,1001,1):
    if i%3!=0: #i를 3으로 나눈 나머지가 0이 아니면 아래행 실행
        Ans=Ans+i
Ans

333667

In [ ]:
# if 문의 사용법
num=9
if num>10: # 뒤에 반드시 ':'을 붙여야 한다.
    print('10보다 큰 숫자입니다') # indentation 사용
elif num<10: # 뒤에 반드시 ':'을 붙여야 한다.
    print('10보다 작은 숫자입니다')
else: # 뒤에 반드시 ':'을 붙여야 한다.
    print('10인 것 같습니다')


10보다 작은 숫자입니다


In [ ]:
# not in 연산자의 활용
A=[i for i in range(1,11)] #1부터 10까지의 자연수
B=[2*i for i in range(1,6)] # 2,4,6,8,10의 짝수
for i in A: # A를 하나씩 증가시켜가면서 반복
    if i not in B: # i가 만일 B에 없으면, 즉 홀수이면
        print(i) # i 값을 출력

1
3
5
7
9


In [ ]:
# 문장이 길 때 '\'를 사용하여 줄바꿈 표시를 할 수 있다.
D ="햄릿은 윌리엄 셰익스피어의 대표작 중 하나입니다.\
햄릿은 왕자인 햄릿이 왕국의 문제와 자신의 내면 갈등을 다루는 이야기입니다.\
햄릿은 윌리엄 셰익스피어의 뛰어난 연극 작품 중 하나로 꼽힙니다."

# len(D)는 문자열의 길이를 return 하는 내장함수
Ans=0
for i in range(len(D)): # 0부터 문자열 길이-1 까지 증가시킴
    if D[i:i+2]=='햄릿': # 차례로 두 글자씩 선택해서 '햄릿'이면
        Ans+=1 # Ans=Ans+1을 Ans +=1로 쓸 수 있음
Ans

4

In [ ]:
# D라는 변수가 어떤 형태인지 확인하는 내장함수 type()을 사용
type(D)

str

In [ ]:
len(D)

105

In [ ]:
# 빈칸을 세는지 확인
D[3]

' '

In [ ]:
import numpy as np
# 0포함 99까지의 자연수를 임의로 20 by 100 by 5 차원의 값으로 출력시킴
D1=np.random.randint(100,size=(20,100,5))
len(D1)

20

In [ ]:
# '햄릿'의 개수를 세기
count_hamlet = D.count('햄릿')

print("문자열 D에서 '햄릿'의 개수:", count_hamlet)

문자열 D에서 '햄릿'의 개수: 4


# 0,1,1,2,3,5,8,…과 같은 피보나치(Fibonacci) 수열의 합 중 10000보다 큰 수 중 가장 작은 수를 구하여라.

In [ ]:
# 피보나치 수열을 생성함과 동시에 부분합의 크기를 체크하면서 10000이 넘는 순간 중단 시킨다.
import numpy as np
F=np.zeros(10000) # 피보나치 수열 10000개를 담기 위한 numpy array를 만듭니다.
F[0],F[1]=0,1 # F[0]=0, F[1]=1 값을 초기값으로 저장
Ans=F[0]+F[1]
for i in range(2,10001): # 2부터 시작해서 10000까지 1씩 증가시킨다.
    F[i]=F[i-1]+F[i-2] # 피보나치 수열의 정의: 직전 2개의 항의 합으로 현재의 항을 생성
    Ans+=F[i] # i번째 항까지의 부분합을 구한다.
    if Ans > 10000: # 부분합이 10000을 넘는다면,
        print(f'{i+1}번째 수열까지의 합이 처음으로 10000을 넘었습니다. 그 값은 {Ans}입니다.')
        break # for 문을 exit 시킨다.


20번째 수열까지의 합이 처음으로 10000을 넘었습니다. 그 값은 10945.0입니다.


In [ ]:
np.sum(F[:20]) # 처음 20개의 합

10945.0

In [ ]:
np.sum(F[:19]) # 처음 19개의 합

6764.0

In [ ]:
# print(f'') 이해하기
# 변수를 print()문과 함께 출력하는 방법은 여러가지가 있다.
a,b=5,10 # a=5, b=10
print(f'a={a},b={b}') # f'{}' 사용
print('a=',a,'b=',b) # 분리해서 사용
print('b={1},a={0}'.format(a,b)) # {}.format() 사용

a=5,b=10
a= 5 b= 10
b=10,a=5


# 1부터 100까지 더할 때, 7로 끝나는 숫자를 제외하고 더하여 보아라.

In [ ]:
Ans=0
for i in range(101): #0부터 100까지 1씩 증가시킴
    if str(i)[-1]=='7': # 숫자 i를 문자열로 만든 str(i)의 마지막 문자열 [-1]이 '7'이면
        continue # 아무 것도 하지 않고 건너 뛴다
    else:
        Ans+=i # Ans의 기존값에 현재의 i를 더한다.
Ans

4530

In [ ]:
# 위 결과의 검증
A1=[i for i in range(1,101)] # 1부터 100까지를 list로 만든다.
A2=[i*10+7 for i in range(10)] # 7,17,...,97의 list를 만든다.
np.sum(A1)-np.sum(A2)

4530

# 사용자 정의 함수 만들기

In [ ]:
# 사용자 정의 함수 만들기
# a 문자열에서 b 문자열의 개수를 반환하는 함수 만들기
def ff(a,b): # def 함수이름(인자들): 의 형식을 취할 것
    return a.count(b) #반환하거자 하는 값을 return 다음에 쓸 것

# 사용자 정의 함수 호출하기
ff('oh my mm god','m')

3

In [ ]:
# 사용자의 정의 함수 만들기 예제 2
# 인자 c=1000 이라는 디폴트 값을 정의할 수 있음.
def hst(a,b,c=1000):
    return a+b+c

# c값을 입력하지 않으면 c=1000이라고 인식함
hst(1,1)

1002

In [ ]:
# c 값을 입력하면 디폴트 값을 무시하게 됨
hst(1,1,1)

3

In [ ]:
# lamda를 이용한 inline 함수 작성
f=lambda x,y:x**2+y**2
f(2,2)

8

## 에라토스테네스의 체

In [2]:
!pip install pytictoc

In [3]:
from pytictoc import TicToc
import numpy as np
timer=TicToc() # 시간측정 객체 만들기
timer.tic() # 측정 시작
n=10000
G_pot=[] # 소수 리스트
for i in range(2,n+1):
    i_pot=[] # i의 약수 리스트
    for j in range(1,i+1):
        if np.mod(i,j)==0: #j는 i의 약수
            i_pot.append(j)
    if len(i_pot) == 2:
        G_pot.append(i)
print(f"{n} 이하의 소수의 개수: {len(G_pot)}")
timer.toc() # 측정후 시간 출력

10000 이하의 소수의 개수: 1229
Elapsed time is 86.565574 seconds.


In [ ]:
def sieve_of_eratosthenes(n):
    # 0부터 n까지 모두 True인 리스트 생성
    is_prime = [True] * (n + 1)

    # 첫번째, 두번째는 False로 설정
    is_prime[0] = is_prime[1] = False

    # 세번째 부터 n의 절반(자연수)까지
    for i in range(2, int(n**0.5) + 1):
        if is_prime[i]: # i번째가 True이면
            # i,2i,3i,....를 모두 False로 설정
            for j in range(i * i, n + 1, i):
                is_prime[j] = False
    # is_prime의 index(num),값(prime)을 하나씩 빼서
    # prime이 True면 index만 추출
    primes = [num for num, prime in enumerate(is_prime) if prime]
    return primes # 총 index를 리턴

In [ ]:
# 사용 예시
n = 10000
timer.tic()
result = sieve_of_eratosthenes(n)
print(f"{n} 이하의 소수의 개수: {len(result)}")

timer.toc()

10000 이하의 소수의 개수: 1229
Elapsed time is 0.002025 seconds.


In [ ]:
timer.tic()
result = sieve_of_eratosthenes(1000000)
print(f"{n} 이하의 소수의 개수: {len(result)}")
timer.toc()

10000 이하의 소수의 개수: 78498
Elapsed time is 0.169341 seconds.


## [하노이 타워](https://www.mathsisfun.com/games/towerofhanoi.html)

In [ ]:
# Recursive Python function to solve the tower of hanoi
Min_Move=0
def TowerOfHanoi(n , source, destination, auxiliary):
    if n==1: # 만일 n=1이면 한번에 끝난다.
        print (f'1 번째 원반을 {source}에서 {destination}으로 옮긴다')
        return # 리턴 값이 없으면 그냥 공란으로 두면 된다.
    # 만일 n>=2이면 n-1개를 먼저 2번기둥으로 옮기는 문제를 풀고
    TowerOfHanoi(n-1, source, auxiliary, destination)
    # n번째 원반을 3번기둥으로 옮긴다.
    print (f'{n} 번째 원반을 {source}에서 {destination}으로 옮긴다')
    # 2번 기둥에 있던 n-1개의 원반을 이제 3번 기둥으로 옮긴다
    TowerOfHanoi(n-1, auxiliary, destination, source)

In [ ]:
# 하노이 타워 문제 풀기
n = 3
TowerOfHanoi(n,'1번기둥','3번기둥','2번기둥')

1 번째 원반을 1번기둥에서 3번기둥으로 옮긴다
2 번째 원반을 1번기둥에서 2번기둥으로 옮긴다
1 번째 원반을 3번기둥에서 2번기둥으로 옮긴다
3 번째 원반을 1번기둥에서 3번기둥으로 옮긴다
1 번째 원반을 2번기둥에서 1번기둥으로 옮긴다
2 번째 원반을 2번기둥에서 3번기둥으로 옮긴다
1 번째 원반을 1번기둥에서 3번기둥으로 옮긴다


In [4]:
# 최소 움직임 회수만 계산해 보자.
def HTowerMove(n):
    if n==1: # n=1이면
        return 1 # 답 1을 return한다.
    else: # n>=2이면
        # n-1일 때 회수의 2배에 1을 더해 주면 된다.
        return 2*HTowerMove(n-1)+1
HTowerMove(3)

7

# 5!를 계산하는 프로그램을 재귀함수를 이용하여 작성해 보아라.

In [ ]:
def fun_factorial(n):
    if n==0 or n==1:
        return 1
    else:
        return n*fun_factorial(n-1)
fun_factorial(5)

120

In [ ]:
Ans=1
for i in range(1,6): # 1부터 5까지 1씩 증가
    Ans*=i # Ana=Ans*i를 왼쪽과 같이 쓸 수 있다.
Ans

120